### ISSUE TITLE
Event Management

### ISSUE THREAD

**Issue by DmytroMelnykm** [DmytroMelnykm/testTaskJoin.To.IT#1]
The primary goal of this task is to create a Django-based REST-Api that manages
events (like conferences, meetups, etc.). The application will allow users to create,
view, update, and delete events. It should also handle user registrations for these
events.

Key Requirements
- Design an Event model with fields such as title, description, date, location,
and organizer.
- Implement CRUD (Create, Read, Update, Delete) operations for the Event
model.
- Basic User Registration and Authentication.
- Event Registration

Bonus Points
- Implement an advanced feature like event search or filtering.
- Add a feature for sending email notifications to users upon event registration.

**Comment by VidyaYadavv1519** [comment]
Hello, I wanted to do this issue,
can you please assign me ??
